"""F6: plain-language explanations, contract summary, and safer-wording
suggestions - all generated by Gemini, grounded in the rule that fired."""
import json

from . import gemini_client
from .rules import Rule


def explain_flag(clause_text: str, rule: Rule) -> dict:
    """Returns {reason, provision, safer_wording} for one flagged clause."""
    prompt = f"""You are a plain-language contract explainer for Indian contract law.
A clause was flagged by the rule "{rule.label}" ({rule.legal_basis}).

Clause text:
\"\"\"{clause_text[:1500]}\"\"\"

Reply with ONLY a JSON object with these keys:
- "reason": 2-3 sentences in plain English explaining why this specific clause is risky for the
  person signing it, referencing the actual wording.
- "provision": the short exact phrase or sentence within the clause that triggers the concern
  (quote it directly from the clause text above).
- "safer_wording": a rewritten, fairer version of this clause that keeps its legitimate purpose
  but removes the one-sided risk."""
    result = gemini_client.generate_json(prompt)
    return {
        "reason": result.get("reason", "").strip(),
        "provision": result.get("provision", "").strip(),
        "safer_wording": result.get("safer_wording", "").strip(),
    }


def summarize_contract(clause_texts: list[str], flags_summary: list[dict]) -> dict:
    """Returns {plain_summary, key_obligations: [str]}."""
    joined = "\n\n".join(f"- {t[:400]}" for t in clause_texts[:40])
    flags_text = "\n".join(
        f"- {f['rule_label']} ({f['severity']}) in clause {f['clause_index']}" for f in flags_summary
    )
    prompt = f"""You are summarizing a commercial contract for a non-lawyer signer in India.

Clauses (excerpts):
{joined}

Flagged risk issues already detected:
{flags_text or "(none)"}

Reply with ONLY a JSON object:
- "plain_summary": 4-6 sentences in plain English describing what this contract is about and the
  overall risk picture, mentioning the flagged issues in context.
- "key_obligations": a JSON array of 4-8 short strings, each one key obligation the signer takes on."""
    result = gemini_client.generate_json(prompt)
    return {
        "plain_summary": result.get("plain_summary", "").strip(),
        "key_obligations": result.get("key_obligations", []) or [],
    }
