"""Curated predatory-clause rule set for Indian contract law (F3).

Each rule is a deterministic keyword/pattern detector over clause text. Detection
is rule-based (auditable, reproducible); the plain-language reason and safer
wording for each hit are generated by Gemini (see services/explain.py) so no
explanation is hard-coded.
"""
import re
from dataclasses import dataclass


@dataclass
class Rule:
    id: str
    label: str
    severity: str  # low / medium / high
    legal_basis: str
    pattern: re.Pattern


RULES: list[Rule] = [
    Rule(
        id="restraint_of_trade",
        label="Restraint of Trade / Non-Compete",
        severity="high",
        legal_basis="Indian Contract Act 1872, Section 27 - agreements restraining trade are void, "
                     "subject to narrow exceptions (e.g. sale of goodwill).",
        pattern=re.compile(
            r"\bnon[- ]compet|restrain(?:t|ing)?\s+(?:of\s+)?trade|shall not (?:engage|work|be employed|"
            r"provide services) (?:in|with|for)|competing business|solicit.{0,40}(?:client|customer|employee)",
            re.IGNORECASE,
        ),
    ),
    Rule(
        id="penalty_clause",
        label="Penalty vs Liquidated Damages",
        severity="medium",
        legal_basis="Indian Contract Act 1872, Section 74 - only a genuine pre-estimate of loss "
                     "(liquidated damages) is enforceable; a punitive penalty is not.",
        pattern=re.compile(
            r"\bpenalty\b|\bpenal(?:ty|ties)\s+(?:of|equal to|amounting)|liquidated damages|"
            r"forfeit(?:ure)?\s+of\s+(?:the\s+)?(?:entire|full|whole)",
            re.IGNORECASE,
        ),
    ),
    Rule(
        id="unilateral_termination",
        label="Unilateral Termination",
        severity="high",
        legal_basis="Contracts should allow both parties reasonable notice and cause for termination; "
                     "one-sided termination rights undermine mutuality under Indian contract principles.",
        pattern=re.compile(
            r"(?:sole|absolute|unfettered)\s+discretion.{0,60}terminat|"
            r"terminat(?:e|ion).{0,60}(?:sole|absolute|unfettered)\s+discretion|"
            r"(?:company|employer|licensor|landlord)\s+may\s+terminate.{0,80}"
            r"(?:without\s+(?:cause|reason|notice)|at any time)|"
            r"terminate\s+(?:this\s+)?(?:agreement|contract).{0,40}without\s+(?:cause|notice|reason)",
            re.IGNORECASE,
        ),
    ),
    Rule(
        id="unlimited_liability",
        label="Unlimited Liability",
        severity="high",
        legal_basis="Absence of a liability cap exposes a party to unbounded, disproportionate risk; "
                     "Indian courts assess reasonableness of liability terms under Section 73/74.",
        pattern=re.compile(
            r"unlimited liability|no limitation (?:of|on) liability|shall be (?:fully|solely|entirely)"
            r"\s+liable\s+for\s+(?:any|all)|without\s+(?:any\s+)?limit(?:ation)?\s+(?:as\s+to|on)\s+liability|"
            r"liable\s+for\s+any\s+and\s+all\s+(?:losses|damages|claims)",
            re.IGNORECASE,
        ),
    ),
    Rule(
        id="one_sided_arbitration",
        label="One-Sided Arbitration",
        severity="medium",
        legal_basis="Arbitration and Conciliation Act 1996 - arbitration clauses naming only one party's "
                     "chosen arbitrator/venue, or barring court recourse for one side, raise fairness concerns.",
        pattern=re.compile(
            r"arbitrat(?:or|ion).{0,80}(?:sole|solely)\s+(?:appointed|chosen|selected)\s+by|"
            r"arbitration\s+shall\s+be\s+(?:conducted|held)\s+(?:solely\s+)?in\s+\w+.{0,40}"
            r"(?:at\s+the\s+(?:option|discretion)\s+of)|"
            r"only\s+(?:the\s+)?(?:company|employer|licensor)\s+(?:may|shall have the right to)\s+"
            r"(?:refer|invoke)\s+arbitration",
            re.IGNORECASE,
        ),
    ),
    Rule(
        id="auto_renewal",
        label="Automatic Renewal / Evergreen Clause",
        severity="medium",
        legal_basis="Auto-renewal without clear opt-out notice can trap a party into unwanted successive "
                     "terms; Consumer Protection Act 2019 disfavours such unfair contract terms for consumers.",
        pattern=re.compile(
            r"automatically\s+renew|auto[- ]renew|shall\s+be\s+deemed\s+renewed|"
            r"renew(?:s|ed)?\s+for\s+(?:successive|additional)\s+(?:period|term)s?\s+unless",
            re.IGNORECASE,
        ),
    ),
    Rule(
        id="ip_overreach",
        label="Intellectual Property Overreach",
        severity="high",
        legal_basis="Copyright Act 1957 / Indian Contract Act - assigning all IP, including pre-existing "
                     "or unrelated work, beyond the scope of engagement is an overreaching term.",
        pattern=re.compile(
            r"all\s+intellectual\s+property.{0,60}(?:whether|including).{0,60}"
            r"(?:prior|pre[- ]existing|unrelated)|"
            r"(?:assign|transfer)s?\s+(?:all|any)\s+(?:right,?\s*title,?\s*and\s+interest|IP|intellectual"
            r"\s+property).{0,80}(?:in perpetuity|worldwide|irrevocably)|"
            r"work\s+made\s+for\s+hire.{0,60}(?:all|any)\s+(?:work|material|output)",
            re.IGNORECASE,
        ),
    ),
    Rule(
        id="no_refund",
        label="No-Refund Clause",
        severity="medium",
        legal_basis="Consumer Protection Act 2019 - blanket no-refund terms, especially combined with "
                     "unilateral termination, can constitute an unfair trade practice.",
        pattern=re.compile(
            r"non[- ]refundable|no\s+refund(?:s)?\s+(?:shall|will)\s+be\s+(?:made|given|provided|issued)|"
            r"not\s+entitled\s+to\s+(?:any\s+)?refund",
            re.IGNORECASE,
        ),
    ),
]

RULES_BY_ID = {r.id: r for r in RULES}


def detect_flags(clause_text: str) -> list[Rule]:
    return [rule for rule in RULES if rule.pattern.search(clause_text)]
